# Site settings
title: MobileMainStreet
description: "Built for people to tell their stories"
url: "http://mstreet.io"

# Build settings
markdown: kramdown
kramdown:
  use_coderay: false
permalink: pretty
encoding: utf-8
